### ISSUE TITLE
Arch Linux package

### ISSUE THREAD

**Issue by ghost** [Maestroschan/Appdisplay-Columns-Gnome-extension-#2]
I just want to thank you for this usefull extension.
I create [gnome-shell-extension-more-columns-in-applications-view-git](https://aur.archlinux.org/packages/gnome-shell-extension-more-columns-in-applications-view-git/) package in Arch Linux AUR repository, for Arch users. please add it to install section on README file.

**Comment by maoschanz** [comment]
thx
