### ISSUE TITLE
Extension fails under GNOME 3.38 with "appdisplayView is undefined"

### ISSUE THREAD

**Issue by x80486** [Maestroschan/Appdisplay-Columns-Gnome-extension-#6]
Looks like this one might need some updates to be able to work under GNOME `3.38`. I'm aware this release changed quite a lot in this regard, but the new `Applications` view is a little bit annoying since all the applications are trying to fit in the smallest space possible.

It would be great if application can be spaced more between them and the number per page/view increased — as this extension does.

**Comment by Pioxis** [comment]
Hello! I have the same issue with Ubuntu 20.10 under Gnome 3.38.1. 
That extension will be updated? 
I heard about new way to menu overview and that should be rewrite to gnome 3.38.1. :(

**Comment by maoschanz** [comment]
>That extension will be updated?

Probably not

**Comment by Pioxis** [comment]
It's sad. That was nice extension :) Thank you for that.

**Comment by mansoormemon** [comment]
I am also getting the same error message on Ubuntu 20.10
